export const ROW_PADDING_TOP = 6
export const ROW_PADDING_BOT = 6

export const MIN_ROW_HEIGHT = 48
export const MIN_ROW_HEIGHT_WITH_PADDING = MIN_ROW_HEIGHT + ROW_PADDING_BOT + ROW_PADDING_TOP

export const HEADER_HEIGHT = 48
