export const ROW_PADDING_TOP = 4
export const ROW_PADDING_BOT = 4

export const MIN_ROW_HEIGHT = 32
export const MIN_ROW_HEIGHT_WITH_PADDING = MIN_ROW_HEIGHT + ROW_PADDING_BOT + ROW_PADDING_TOP

export const MIN_CELL_RESIZE_WIDTH = 100
export const MAX_CELL_RESIZE_WIDTH = 100000

export const HEADER_HEIGHT = 38
