import React from 'react'

import SimpleTextCellRenderer from './components/table/cellRenderers/common/SimpleTextCellRenderer'
import SimpleDateCellRenderer from './components/table/cellRenderers/common/SimpleDateCellRenderer'
import SinglePlaneCellRenderer from './components/table/cellRenderers/plane/SinglePlaneCellRenderer'
import SimpleCurrencyCellRenderer from './components/table/cellRenderers/currency/SimpleCurrencyCellRenderer'

const ColumnsConfig = [
  {
    isStickToLeft: false,
    isStickToRight: false,
    isResizeDisabled: false,
    isSortDisabled: false,
    isHidden: false,
    label: 'Id',
    dataKey: 'id',
    width: null,
    defaultWidth: 50,
    cellRenderer: ({ rowData }) => <SimpleTextCellRenderer text={rowData.id} />,
  },
  {
    isStickToLeft: false,
    isStickToRight: false,
    isResizeDisabled: false,
    isSortDisabled: false,
    isHidden: false,
    label: 'Date',
    dataKey: 'date',
    width: null,
    defaultWidth: 100,
    cellRenderer: ({ rowData }) => <SimpleDateCellRenderer date={rowData.date} />,
  },
  {
    isStickToLeft: false,
    isStickToRight: false,
    isResizeDisabled: false,
    isSortDisabled: false,
    isHidden: false,
    label: 'Trip №',
    dataKey: 'tripNumber',
    width: null,
    defaultWidth: 75,
    cellRenderer: ({ rowData }) => <SimpleTextCellRenderer text={rowData.tripNumber} />,
  },
  {
    isStickToLeft: false,
    isStickToRight: false,
    isResizeDisabled: false,
    isSortDisabled: false,
    isHidden: false,
    label: 'Category',
    dataKey: 'category',
    width: null,
    defaultWidth: 200,
    cellRenderer: ({ rowData }) => <SimpleTextCellRenderer text={rowData.category.name} />,
  },
  {
    isStickToLeft: false,
    isStickToRight: false,
    isResizeDisabled: false,
    isSortDisabled: false,
    isHidden: false,
    label: 'Sub Category',
    dataKey: 'subCategory',
    width: null,
    defaultWidth: 200,
    cellRenderer: ({ rowData }) => <SimpleTextCellRenderer text={rowData.subCategory.name} />,
  },
  {
    isStickToLeft: false,
    isStickToRight: false,
    isResizeDisabled: false,
    isSortDisabled: false,
    isHidden: false,
    label: 'Aircraft',
    dataKey: 'plane',
    width: null,
    defaultWidth: 100,
    cellRenderer: ({ rowData }) => <SinglePlaneCellRenderer plane={rowData.plane} />,
  },
  {
    label: 'Cost',
    dataKey: 'cost',
    width: null,
    defaultWidth: 100,
    cellRenderer: ({ rowData }) => <SimpleCurrencyCellRenderer data={rowData.cost} />,
  },
  {
    label: 'Cost Original',
    dataKey: 'costOriginal',
    width: null,
    defaultWidth: 120,
    cellRenderer: ({ rowData }) => <SimpleCurrencyCellRenderer data={rowData.costOriginal} />,
  },
  {
    isStickToLeft: false,
    isStickToRight: false,
    isResizeDisabled: false,
    isSortDisabled: false,
    isHidden: false,
    label: 'Total',
    dataKey: 'total',
    width: null,
    defaultWidth: 100,
    cellRenderer: ({ rowData }) => <SimpleCurrencyCellRenderer data={rowData.total} />,
  },
  {
    isStickToLeft: false,
    isStickToRight: false,
    isResizeDisabled: false,
    isSortDisabled: false,
    isHidden: false,
    label: 'Total Original',
    dataKey: 'totalOriginal',
    width: null,
    defaultWidth: 150,
    cellRenderer: ({ rowData }) => <SimpleCurrencyCellRenderer data={rowData.totalOriginal} />,
  },
  {
    isStickToLeft: false,
    isStickToRight: false,
    isResizeDisabled: false,
    isSortDisabled: false,
    isHidden: false,
    label: 'Ex. Rate',
    dataKey: 'exchangeRate',
    width: null,
    defaultWidth: 100,
    cellRenderer: ({ rowData }) => <SimpleTextCellRenderer text={rowData.exchangeRate} />,
  },
]

export default ColumnsConfig
