const ColumnsConfig = [
  {
    isStickToLeft: false,
    isStickToRight: false,
    isResizeDisabled: false,
    isSortDisabled: false,
    isHidden: false,
    label: 'Id',
    dataKey: 'id',
    width: null,
    defaultWidth: 50,
  },
  {
    isStickToLeft: false,
    isStickToRight: false,
    isResizeDisabled: false,
    isSortDisabled: false,
    isHidden: false,
    label: 'Date',
    dataKey: 'date',
    width: null,
    defaultWidth: 100,
  },
  {
    isStickToLeft: false,
    isStickToRight: false,
    isResizeDisabled: false,
    isSortDisabled: false,
    isHidden: false,
    label: 'Trip №',
    dataKey: 'tripNumber',
    width: null,
    defaultWidth: 75,
  },
  {
    isStickToLeft: false,
    isStickToRight: false,
    isResizeDisabled: false,
    isSortDisabled: false,
    isHidden: false,
    label: 'Category',
    dataKey: 'category',
    width: null,
    defaultWidth: 200,
  },
  {
    isStickToLeft: false,
    isStickToRight: false,
    isResizeDisabled: false,
    isSortDisabled: false,
    isHidden: false,
    label: 'Sub Category',
    dataKey: 'subCategory',
    width: null,
    defaultWidth: 200,
  },
  {
    isStickToLeft: false,
    isStickToRight: false,
    isResizeDisabled: false,
    isSortDisabled: false,
    isHidden: false,
    label: 'Aircraft',
    dataKey: 'plane',
    width: null,
    defaultWidth: 100,
  },
  {
    label: 'Cost',
    dataKey: 'cost',
    width: null,
    defaultWidth: 100,
  },
  {
    label: 'Cost Original',
    dataKey: 'costOriginal',
    width: null,
    defaultWidth: 120,
  },
  {
    isStickToLeft: false,
    isStickToRight: false,
    isResizeDisabled: false,
    isSortDisabled: false,
    isHidden: false,
    label: 'Total',
    dataKey: 'total',
    width: null,
    defaultWidth: 100,
  },
  {
    isStickToLeft: false,
    isStickToRight: false,
    isResizeDisabled: false,
    isSortDisabled: false,
    isHidden: false,
    label: 'Total Original',
    dataKey: 'totalOriginal',
    width: null,
    defaultWidth: 150,
  },
  {
    isStickToLeft: false,
    isStickToRight: false,
    isResizeDisabled: false,
    isSortDisabled: false,
    isHidden: false,
    label: 'Ex. Rate',
    dataKey: 'exchangeRate',
    width: null,
    defaultWidth: 100,
  },
]

export default ColumnsConfig
